layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: GraphQL
    web_url: https://graphql.org/
    image_url: https://raw.githubusercontent.com/facebook/graphql/master/resources/GraphQL%20Logo.png

  - name: VirtualCast
    web_url: https://virtualcast.jp/
    image_url: https://pbs.twimg.com/profile_images/983546515837804544/zSvLqGp8_400x400.jpg

  - name: CRA
    web_url: https://github.com/facebook/create-react-app
    image_url: https://facebook.github.io/create-react-app/img/logo.svg
